Un-hardcoded config
TechnicJelle/BlueMapOfflinePlayerMarkers pull request #18
Opened 2022-10-22 02:07 UTC by LOOHP

This PR makes the config editable

2022-10-22 23:28 UTC, TechnicJelle commented on src/main/java/com/technicjelle/bluemapofflineplayermarkers/Config.java
> +		markerSetId = plugin.getConfig().getString("MarkerSetId");
I don't think users of this plugin need to be able to change the MarkerSet ID. It's [so well hidden](https://discord.com/channels/665868367416131594/751804128749027421/1033518402209329192) in the BlueMap interface that basically no-one would ever see it anyway.
Removing this from the config would be better, in my opinion.
That takes away an option in the config for users to be confused about too.

2022-10-22 23:28 UTC, TechnicJelle commented on src/main/java/com/technicjelle/bluemapofflineplayermarkers/Config.java
> +		markerSetId = plugin.getConfig().getString("MarkerSetId");
Of course the MarkerSet Name should stay in the config.

2022-10-23 00:53 UTC, TechnicJelle requested changes
Looks pretty good, thank you very much!
Please do check these little thingies, though, if possible ^-^

2022-10-23 00:53 UTC, TechnicJelle commented on src/main/resources/config.yml
> +# Examples:
These examples use `playerheadsAPI:` and not `SkinURL`

2022-10-23 00:53 UTC, TechnicJelle commented on src/main/resources/config.yml
> +#Whether to use bluemaps own player icons instead of downloading manuelly
typo: `#Whether to use BlueMap's own player icons, instead of downloading manually`

2022-10-23 00:53 UTC, TechnicJelle commented on src/main/java/com/technicjelle/bluemapofflineplayermarkers/Main.java
> +				Files.copy(inputStream, configFile.toPath());
I [recently](https://github.com/TechnicJelle/BlueMapChatMarkers/blob/main/src/main/java/com/technicjelle/bluemapchatmarkers/Main.java#L49-L56) did this like so:
```java
try {
	Files.copy(getResource("textStyle.css"), configFile);
```
Feels a lot simpler to me, so without those classloaders and streams :)

2022-10-23 00:57 UTC, TechnicJelle commented
Please also write in the PR text which issues this closes :)

2022-10-23 01:18 UTC, TechnicJelle commented
Also, if possible, add in a config.yml version checker, so the plugin can detect if it was updated from an older version and can alert the user that the config should be updated. Example of this: https://github.com/TechnicJelle/BlueMapFloodgate/blob/main/src/main/java/com/technicjelle/bluemapfloodgate/Main.java#L73

2022-10-23 13:35 UTC, LOOHP commented on src/main/resources/config.yml
> +#The place to get the playerhead icons from. Leave empty to use BlueMap's own files
I feel like having it separate is a better option, it paves the way to adding fallback skin download in the future.

2022-10-23 13:36 UTC, LOOHP commented
> Also, if possible, add in a config.yml version checker, so the plugin can detect if it was updated from an older version and can alert the user that the config should be updated. Example of this: https://github.com/TechnicJelle/BlueMapFloodgate/blob/main/src/main/java/com/technicjelle/bluemapfloodgate/Main.java#L73, but if you have a better way for doing this kind of thing, by all means :D

I feel like the config is small enough for now that this isn't needed (at least for the near future as well)

2022-10-23 21:23 UTC, TechnicJelle approved these changes
Good fixes!

2022-10-23 21:24 UTC, TechnicJelle commented on src/main/resources/config.yml
> +#The place to get the playerhead icons from. Leave empty to use BlueMap's own files
That's a very fair point!

2022-10-23 21:25 UTC, TechnicJelle commented
> I feel like the config is small enough for now that this isn't needed (at least for the near future as well)

That's fair, for now, yeah, I suppose..

2022-10-24 00:34 UTC, TechnicJelle commented
Just tested it out and it works nicely. Thank you very much for your contribution! :D

2022-10-24 00:34 UTC, merged